export const GET_CARS_REQUEST = 'GET_CARS_REQUEST';
export const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
export const GET_CARS_ERROR = 'GET_CARS_ERROR';

export const REMOVE_CAR_REQUEST = 'REMOVE_CAR_REQUEST';
export const REMOVE_CAR_SUCCESS = 'REMOVE_CAR_SUCCESS';
export const REMOVE_CAR_ERROR = 'REMOVE_CAR_ERROR';

export const EDIT_CAR_REQUEST = 'EDIT_CAR_REQUEST';
export const EDIT_CAR_SUCCESS = 'EDIT_CAR_SUCCESS';
export const EDIT_CAR_ERROR = 'EDIT_CAR_ERROR';

export const CREATE_CAR_REQUEST = 'CREATE_CAR_REQUEST';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const CREATE_CAR_ERROR = 'CREATE_CAR_ERROR';